# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

generateCloneTraj <- function(NCell, M, dupRate, deathRate, diffRate, dt, tEnd, E0) {
    .Call('_SLCDP_generateCloneTraj', PACKAGE = 'SLCDP', NCell, M, dupRate, deathRate, diffRate, dt, tEnd, E0)
}

